title: Qingyi Si (佀庆一)
logo: /assets/img/logo.png
description: Ph.D. Student in Institute of Information Engineering, CAS – Beijing
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
