title: Qingyi Si (佀庆一)
logo: /assets/img/zhaopian.png
description: Institute of Information Engineering, Chinese Academy of Sciences 89-A, Minzhuang Rd, Haidian District, Beijing, 100093, China
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
